spring:
  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://rm-wz937i3p0rfl26651yo.mysql.rds.aliyuncs.com:3306/content_center
    hikari:
      username: itmuch
      password: 5dHfoGzlqKmRbInh
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: content-center
#        namespace: 82e2385f-bb78-42a7-8fc2-24f0824732b5
        cluster-name: BJ

    sentinel:
      filter:
        # 关闭掉对Spring MVC端点的保护
        enabled: false
#      transport:
#        # 指定sentinel控制台的地址
#        dashboard: localhost:8090


server:
  port: 8010

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#ribbon:
#  eager-load:
#    enabled: true
#    clients: user-center
logging:
  level:
    com.itmuch.contentcenter.feignclient.UserCenterFeignClient: debug


# 细粒度配置
#feign:
#  sentinel:
#    # 为 Feign 整合 Sentinel
#    enabled: true
#  client:
#    config:
#      user-center:
#        loggerLevel: full
feign:
  client:
    config:
      default:
        loggerLevel: full
  httpclient:
    # 让Feign使用 Apache httpclient做请求
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
resttemplate:
  sentinel:
    # 关闭 @SentinelRestTemplate注解
    enabled: true
#feign:
#  sentinel:
#    enabled: true
ahas:
  namespace: default
  license: c700d5b242aa45108667fad9a6a86f5f

project:
  name: content-center

